version: '3'
services:
  api:
    build:
      context: ./
    ports:
      - "5000:80"
    container_name: bolton-api-container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - bolton-network
  sql:
    image: microsoft/mssql-server-linux:latest
    ports:
      - "5005:1433"
    environment:
      SA_PASSWORD: "Password1"
      ACCEPT_EULA: "Y"
    container_name: bolton-sql-container
    networks:
      - bolton-network
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   ports:
  #     - "5010:5672"
  #     - "5015:15672"
  #   container_name: bolton-rabbitmq-container
  #   networks:
  #     - bolton-network

# since both service and db are in the same host, service connects to db using the container name idp-db-host 
# in the connection string
networks: 
  bolton-network:



# d for daemon mode
# docker-compose up -d 
# docker-compose down