version: '3'
services:
  api:
    build:
      context: ./
    ports:
      - "5000:5000"
    container_name: bolton-api-container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - bolton-network
  sql-db:
    image: microsoft/mssql-server-linux:latest
    ports:
      - "5500:1433"
    environment:
      SA_PASSWORD: "Password1"
      ACCEPT_EULA: "Y"
    container_name: bolton-sql-db-container
    networks:
      - bolton-network

# since both service and db are in the same host, service connects to db using the container name idp-db-host 
# in the connection string
networks: 
  bolton-network: