site_name: BoltOn
nav:
    - Introduction: index.md
    - Requestor: requestor.md
    - Data: data.md
    - Bus: bus.md
    - CQRS: cqrs.md
    - Utilities: utilities.md
    - Optional: optional.md
    - Samples: samples.md
    - CLI: cli.md
    - CI & CD: build.md
theme: readthedocs

