site_name: BoltOn
nav:
    - Introduction: index.md
    - Mediator: mediator.md
    - Data: data.md
    - Bus: bus.md
    - CQRS: cqrs.md
    - Utilities: utilities.md
    - Optional: optional.md
theme: readthedocs

