version: '3'
services:
  sql:
    image: microsoft/mssql-server-linux:latest
    ports:
      - "5005:1433"
    environment:
      SA_PASSWORD: "Password1"
      ACCEPT_EULA: "Y"
    container_name: bolton-sql-container
    networks:
      - bolton-network
  console:
    environment:
      - CONSOLE_ENVIRONMENT=Docker
    build:
      context: ./
      dockerfile: Console.Dockerfile
    container_name: bolton-console-container
    depends_on:
      - sql
    networks:
      - bolton-network
    # 2 lines below are equivalent to docker run -it, to keep the console running 
    stdin_open: true 
    tty: true        
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    build:
      context: ./
      dockerfile: WebApi.Dockerfile
    ports:
      - "5000:80"
    container_name: bolton-api-container
    depends_on:
      - sql
      - console
    networks:
      - bolton-network

networks: 
  bolton-network:

# d detached mode or background mode
# docker-compose up -d --build 

# --rmi remove local images
# docker-compose down --rmi local