version: '3'
services:
  sql:
    image: microsoft/mssql-server-linux:latest
    ports:
      - "5005:1433"
    environment:
      SA_PASSWORD: "Password1"
      ACCEPT_EULA: "Y"
    container_name: bolton-sql-container
  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: bolton-redis-container

# docker-compose -f docker-compose-local.yml up -d
# docker-compose -f docker-compose-local.yml down