name: CD

on: 
  push:
    branches:
      - develop
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.1
    - name: Run publish.ps1
      run: pwsh './build/publish.ps1' ${GITHUB_REF##*/} ${{ secrets.NuGetApiKey }}
