name: CI

on: 
  push:
    branches:
      - build

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: Run build.ps1
      run: pwsh './build/build.ps1' ${GITHUB_REF##*/} ${{ secrets.NuGetApiKey }}
